version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: backend
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    container_name: frontend
    depends_on:
      - backend
